dist: trusty
language: node_js
node_js:
- stable
script:
- npm run coverage
after_success:
- npm run publish-coverage
branches:
   only: master
notifications:
   email:
      recipients:
      278899085@qq.com
      on_success: never
      on_failure: always
